name = "ENS_26"
defaultTargets = ["ENS_26"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
linter.tacticAnalysis.introMerge = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[lean_lib]]
name = "ENS_26"
